export const blogs_xx = [
  {
    id: 7,
    img: '/images/photo-7.jpg',
    remote_img: '',
    category: 'travel',
    title: 'sun rise from the mountain',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
];

export const all_blogs_xx = [
  {
    id: 1,
    img: '/images/photo-1.jpg',
    remote_img: '',
    category: 'lifestyle',
    title: 'why coffee is awesome',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 2,
    img: '/images/photo-2.jpg',
    remote_img: '',
    category: 'travel',
    title: 'travel to paris',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 3,
    img: '/images/photo-3.jpg',
    remote_img: '',
    category: 'lifestyle',
    title: 'coffee brings friendship',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 4,
    img: '/images/photo-4.jpg',
    remote_img: '',
    category: 'lifestyle',
    title: 'coffee make you feel good',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 5,
    img: '/images/photo-5.jpg',
    remote_img: '',
    category: 'lifestyle',
    title: 'coffee make you calm',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 6,
    img: '/images/photo-6.jpg',
    remote_img: '',
    category: 'travel',
    title: '101 tower in Taipei',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 7,
    img: '/images/photo-7.jpg',
    remote_img: '',
    category: 'travel',
    title: 'sun rise from the mountain',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 8,
    img: '/images/photo-8.jpg',
    remote_img: '',
    category: 'travel',
    title: 'serene lake with trees',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
  {
    id: 9,
    img: '/images/photo-9.jpg',
    remote_img: '',
    category: 'travel',
    title: 'rocks of queen head in Yehliu, Taiwan',
    desc: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit.',
  },
];
